import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { greycliffBold, greycliffMedium, greycliffRegular } from "./styles";
import CustomCursor from "./components/customcursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CustomCursor />
      <body className={`${greycliffBold.variable} ${greycliffMedium.variable} ${greycliffRegular.variable}`}>{children}</body>
    </html>
  );
}
